defaults:
  - _self_

# Disable Hydra changing working directory so relative paths work
hydra:
  job:
    chdir: false

# Reproducibility
seed: 42

# Data paths and splitting
data:
  dir: data/earthquake_dataset             # Root folder containing 'labels', 'pre-disaster', 'post-disaster'
  train_split: 0.8             # Fraction of data used for training
  feature_cols:
    - mag
    - rupture_length_km
    - mmi
    - center_dist_km
    - center_depth_eff_km
    # - depth_km
    # - moment_Nm
    # - epicenter_elev_m
    # - center_elev_m
    # - center_rel_elev_m

# Augmentations (Albumentations style)
augmentations:
  # All augmentations produce 512x512 images so predicted masks stay aligned with
  # original building polygons.
  train:
    - RandomResizedCrop:
        size: 
          - 512
          - 512
        scale:
          - 0.8
          - 1.0
        ratio:
          - 0.75
          - 1.3333333333
    - Normalize: {}
    - HorizontalFlip:
        p: 0.5
    - VerticalFlip:
        p: 0.5
    - RandomBrightnessContrast:
        p: 0.2
  val:
    - Resize:
        height: 512
        width: 512
    - Normalize: {}

# Model configuration
model:
  name: unet    # options: unet, deeplabv3plus, unetplusplus, conditional_unet
                            # conditional_deeplabv3plus, conditional_unetplusplus
  is_conditional: false
  num_classes: 4
  encoder: resnet34
  encoder_weights: imagenet
  vec_dim: null

# Loss configuration
loss:
  name: cross_entropy # options: cross_entropy, dice, cross_entropy_dice, building_pooled
  # pixel_loss: cross_entropy
  # pixel_weight: 1.0
  # building_weight: 1.0
  # building_background_id: 0
  # building_ignore_index: -100
  # dice_weight: 1.0

# Training hyperparameters
training:
  batch_size: 8 # 8, 16, 24, 32
  epochs: 200
  lr: 1e-4
  weight_decay: 1e-5
  device: cuda  # automatically falls back to CPU if unavailable
  checkpoint_dir: checkpoints
  checkpoint_freq: 10

# Logging settings
logging:
  wandb_project: eq-damage
  wandb_dir: wandb
  wandb_name: unet_512_1e-4_cross_entropy

evaluation:
  building_metrics:
    enabled: true
    raise_on_missing: false
    log_centroid_overlays: true
    max_overlay_samples: 4
