defaults:
  - _self_

# Disable Hydra changing working directory so relative paths work
hydra:
  job:
    chdir: false

# Reproducibility
seed: 42

# Data paths and splitting
data:
  dir: data/earthquake_dataset             # Root folder containing 'labels', 'pre-disaster', 'post-disaster'
  train_split: 0.8             # Fraction of data used for training

# Augmentations (Albumentations style)
augmentations:
  train:
    - Resize:
        height: 256
        width: 256
    - Normalize: {}
    - RandomCrop:
        height: 224
        width: 224
    - HorizontalFlip:
        p: 0.5
    - VerticalFlip:
        p: 0.5
    - RandomBrightnessContrast:
        p: 0.2
  val:
    - Resize:
        height: 224
        width: 224
    - Normalize: {}
    
# Model configuration
model:
  name: unet
  encoder: resnet34
  encoder_weights: imagenet
  num_classes: 3

# Training hyperparameters
training:
  batch_size: 32
  epochs: 100
  lr: 1e-4
  weight_decay: 1e-5
  device: cuda
  checkpoint_dir: checkpoints

# Logging settings
logging:
  wandb_project: eq-damage
  wandb_dir: wandb
